module.exports = {
  preset: "jest-expo",
  transformIgnorePatterns: [
    "[/\\\\](?:node_modules|\\.pnpm)[/\\\\](?!.*((jest-)?react-native|@react-native(-community)?|@react-native/js-polyfills|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|uuid|moti))",
  ],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  collectCoverageFrom: [
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "hooks/**/*.{ts,tsx}",
    "utils/**/*.{ts,tsx}",
    "!**/*.d.ts",
    "!**/coverage/**",
    "!**/node_modules/**",
    "!**/.expo/**",
    "!**/babel.config.js",
    "!**/jest.setup.js",
    "!**/jest.config.js",
    "!**/tailwind.config.js",
    "!**/react-native.config.js",
    "!**/.eslintrc.js",
    "!app/+html.tsx",
    "!app/_layout.tsx",
    "!app/+not-found.tsx",
  ],
  testPathIgnorePatterns: [
    "/node_modules/",
    "/.vscode/",
    "/.worktrees/",
    "/.agent/",
    "/.gemini/",
    "/river-reviewer/",
  ],
};
